image: miich43l/vaddinn123:latest
variables:
  MAVEN_CLI_OPTIONS: "--batch-mode"

stages:
  - build

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTIONS clean package -Pproduction -e
  artifacts:
    paths:
      - target/*.jar
