name: Java CI with Maven

# on Push and Pull-Requests run this workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest # defining underlaying OS
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2 #checkout Java
        with: # defining the Java Package paramter e.g. 16
          java-version: "16"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn -B package --file pom.xml # -B = build the application --file using pom.xm

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:  # defining the Java Package paramter e.g. 16
          java-version: "16"
          distribution: "adopt"
      - name: Test application
        run: mvn test -e # test the application running
